<a href="https://colab.research.google.com/github/kuuuun/python_jupyter_notes/blob/main/chapter08_LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# chapter08 线性代数

In [2]:
import numpy as np

矩阵 * 矩阵 就是矩阵乘法  
矩阵 * 向量 就是矩阵的变换  
向量 * 向量 就是向量的点积

In [3]:
# 定义两个矩阵
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("矩阵 A:\n", A)
print("矩阵 B:\n", B)

# 1. 逐元素乘法 (*)
# 对应位置相乘：1*5, 2*6, ...
print("\n逐元素乘法 (A * B):\n", A * B)

# 2. 矩阵乘法 (@)
# 行乘列：1*5+2*7, 1*6+2*8, ...
print("\n矩阵乘法 (A @ B):\n", A @ B)

# 3. 向量的点积
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
# 1*4 + 2*5 + 3*6 = 32
print(f"\n向量内积 (v1 @ v2): {v1 @ v2}")

矩阵 A:
 [[1 2]
 [3 4]]
矩阵 B:
 [[5 6]
 [7 8]]

逐元素乘法 (A * B):
 [[ 5 12]
 [21 32]]

矩阵乘法 (A @ B):
 [[19 22]
 [43 50]]

向量内积 (v1 @ v2): 32


## numpy.linalg 工具箱

|函数|	描述|	数学含义|
|---|---|---|
|np.linalg.inv(A)|	求逆矩阵	|A−1A^{-1} A − 1|
|np.linalg.det(A)|	求行列式	|$|
|np.linalg.norm(A)|	求范数（模长）|	∣A∣|A| ∣ A ∣|
|np.linalg.eig(A)|	特征值分解|	Av=λvAv = \lambda v A v = λ v|
|np.linalg.svd(A)|	奇异值分解|	SVD|
|np.linalg.solve(A, b)|	解方程组|	Ax=bAx = b A x = b|


In [3]:
# 系数矩阵 A
A = np.array([[3, 1],
              [1, 2]])
# 结果向量 b
b = np.array([9, 8])

# 错误做法（不推荐）：显式求逆
# x_bad = np.linalg.inv(A) @ b

# 正确做法：使用 solve
x = np.linalg.solve(A, b)

print(f"解得: x={x[0]:.1f}, y={x[1]:.1f}")

# 验证结果: A @ x 应该等于 b
# 使用 np.allclose 比较浮点数，不要用 ==
is_correct = np.allclose(A @ x, b)
print(f"验证结果是否正确: {is_correct}")

解得: x=2.0, y=3.0
验证结果是否正确: True


In [4]:
# 创建一个对称矩阵（对称矩阵的特征向量总是正交的，性质很好）
M = np.array([[1, 2],
              [2, 1]])

# 计算特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(M)

print("特征值:", eigenvalues)
print("特征向量 (每一列是一个向量):\n", eigenvectors)

# 验证: M @ v = lambda * v
v0 = eigenvectors[:, 0]
lambda0 = eigenvalues[0]

lhs = M @ v0           # 左边: 矩阵 x 向量
rhs = lambda0 * v0     # 右边: 标量 x 向量

print("\n验证特征值性质:", np.allclose(lhs, rhs))

特征值: [ 3. -1.]
特征向量 (每一列是一个向量):
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

验证特征值性质: True


## 高维矩阵乘法

In [3]:
# 模拟 10 个样本，每个样本是一个 2x3 的矩阵
A_batch = np.random.rand(10, 2, 3)

# 模拟 10 个样本，每个样本是一个 3x4 的矩阵
B_batch = np.random.rand(10, 3, 4)

# 我们想对这 10 个样本分别做矩阵乘法
# 结果应该是 (10, 2, 4)
C_batch = A_batch @ B_batch

print(f"A 形状: {A_batch.shape}")
print(f"B 形状: {B_batch.shape}")
print(f"结果形状: {C_batch.shape}")

# 验证第一个样本
# C_batch[0] 应该等于 A_batch[0] @ B_batch[0]
print("验证 Batch 0:", np.allclose(C_batch[0], A_batch[0] @ B_batch[0]))

A 形状: (10, 2, 3)
B 形状: (10, 3, 4)
结果形状: (10, 2, 4)
验证 Batch 0: True
