<a href="https://colab.research.google.com/github/kuuuun/python_jupyter_notes/blob/main/chaptor05_ufuncs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# chaptor05 Ufuncs

In [2]:
import numpy as np

## 与列表推导式的性能对比

In [ ]:
import math
import time

# 准备 500 万个随机数
N = 5_000_000
rng = np.random.default_rng(42)
data_np = rng.random(N)
data_list = data_np.tolist()

print(f"数据量: {N}")

# === 选手 A: Python 列表推导式 + math.sin ===
start = time.time()
res_list = [math.sin(x) for x in data_list]
end = time.time()
print(f"Python Math 耗时: {end - start:.4f} 秒")

# === 选手 B: NumPy Ufunc ===
start = time.time()
# np.sin 就是一个典型的 Ufunc
res_np = np.sin(data_np)
end = time.time()
print(f"NumPy Ufunc 耗时: {end - start:.4f} 秒")

数据量: 5000000
Python Math 耗时: 0.2954 秒
NumPy Ufunc 耗时: 0.0556 秒


## 内存优化：out 参数的妙用

In [ ]:
import numpy as np

# 创建一个较大的数组
large_arr = np.arange(10)
print("原始地址:", id(large_arr))

# 方式 1：常规写法 (创建了新数组，然后重新赋值给变量名)
# 这在中间过程中会产生临时数组
large_arr = np.multiply(large_arr, 2)
print("方式1后地址:", id(large_arr)) # 地址变了，说明发生了内存分配

# 方式 2：使用 out 参数 (原地修改)
# 没有任何临时数组产生
np.multiply(large_arr, 2, out=large_arr)
print("方式2后地址:", id(large_arr)) # 地址没变！

# 甚至可以用切片作为 out 的目标
# 只把前 5 个元素变成负数
np.negative(large_arr[:5], out=large_arr[:5])
print("局部修改后:", large_arr)

原始地址: 138461323149104
方式1后地址: 138461323147760
方式2后地址: 138461323147760
局部修改后: [  0  -4  -8 -12 -16  20  24  28  32  36]


## np.add.reduce(arr,axis=0) 等同于 np.sum(arr,axis=0)

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr.shape)

# 等同于 np.sum(arr, axis=0)
result_a0 = np.add.reduce(arr, axis=0)
print(result_a0)
# 输出: [12 15 18]
result_a1 = np.add.reduce(arr, axis=1)
print(result_a1)

(3, 3)
[12 15 18]
[ 6 15 24]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr.shape)

# 等同于 np.sum(arr, axis=0)
result_a0 = np.sum(arr,axis=0)
print(result_a0)
# 输出: [12 15 18]
result_a1 = np.sum(arr,1)
print(result_a1)

(3, 3)
[12 15 18]
[ 6 15 24]


## 检查数组是否已排序：

这是一个经典的用法。通过比较“当前元素 < 下一个元素”是否在所有位置都成立。

In [ ]:
arr = np.array([1, 3, 2, 4])

# 检查是否 arr[i] < arr[i+1] 对所有 i 都成立
# np.less 就是 <
is_sorted = np.logical_and.reduce(np.less(arr[:-1], arr[1:]))
print(is_sorted)  # False (因为 3 > 2)

False


## 检查数值范围：

虽然通常用 (a < arr) & (arr < b)，但在某些需要动态处理多个条件的循环中，reduce 会很有用。

In [ ]:
# 检查 arr 是否都在 (0, 10) 范围内
arr = np.array([1, 5, 8])
conditions = [arr > 0, arr < 10]
# 将多个条件合并：必须同时满足 >0 且 <10
in_range = np.logical_and.reduce(conditions)
print(in_range)  # [True True True]

[ True  True  True]


## 二维数组：检查“行”或“列”

这是它最实用的地方，配合 axis 参数可以检查矩阵的特定维度。

In [3]:
# 创建一个二维数组
# 假设每一行代表一个学生的各科成绩是否及格 (True=及格, False=挂科)
scores = np.array([[True,  True,  True],   # 学生A 全过
                   [True,  False, True],   # 学生B 挂了一科
                   [True,  True,  False]]) # 学生C 挂了一科

all_passed = np.logical_and.reduce(scores, axis=1)
print(all_passed)  # [ True False False]
# 说明：只有第0个学生（A）全科及格

no_one_failed = np.logical_and.reduce(scores, axis=0)
print(no_one_failed)  # [ True False False]
# 说明：只有第0列（第一科）没有人挂科

[ True False False]
[ True False False]


## accumulate：记录足迹

它和 reduce 很像，但它保留中间过程的每一步结果。

np.add.accumulate = np.cumsum (累积和)
np.multiply.accumulate = np.cumprod (累积积)
这在时间序列分析（如股票价格走势）中是核心操作。

In [4]:
# 假设初始股价是 100元，后面是每天的变化率（百分比）
initial_price = 100
daily_returns = np.array([1.02, 0.98, 1.05, 0.92, 1.10])
# 2%涨, 2%跌, 5%涨, 8%跌, 10%涨

# 计算累积收益率 (这就是 np.cumprod)
cumulative_returns = np.multiply.accumulate(daily_returns)
print("累积收益率:", cumulative_returns)
# 输出: [1.02 0.9996 1.04958 0.9656124 1.06217364]

# 计算每天的实际股价
stock_price = initial_price * cumulative_returns
print("每日股价:", stock_price)
# 输出: [102. 99.96 104.958 ...] -> 这就是一条完整的K线轨迹！

累积收益率: [1.02       0.9996     1.04958    0.9656136  1.06217496]
每日股价: [102.        99.96     104.958     96.56136  106.217496]


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# axis=0: 沿着行记录（垂直方向累加）
print(np.add.accumulate(arr_2d, axis=0))
# 输出:
# [[1 2 3]       <- 第一行原样
#  [5 7 9]]      <- 第一行 + 第二行

# axis=1: 沿着列记录（水平方向累加）
print(np.add.accumulate(arr_2d, axis=1))
# 输出:
# [[ 1  3  6]    <- 第一行内部累加: 1, 1+2, 1+2+3
#  [ 4  9 15]]   <- 第二行内部累加: 4, 4+5, 4+5+6

[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


## outer：外积（制作网格）
它将第一个数组的每个元素与第二个数组的每个元素两两配对运算。
我们在第 4 章用广播实现了九九乘法表，其实用 outer 更直观：

## np.multiply.outer: 这是外积操作。它会把第一个数组的每个元素和第二个数组的每个元素相乘。

在 NumPy 中，np.outer 的作用是计算两个向量的外积。你可以把它理解为：拿第一个向量的每一个元素，去乘以第二个向量的全部元素，从而铺开一张二维的网12。


In [ ]:
# 一行代码搞定乘法表
table = np.multiply.outer(np.arange(10), np.arange(10))
print(table)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]


## at：原地无缓冲修改

at 是 NumPy 1.8 引入的神器。当你尝试用 i += 1 的逻辑处理重复索引时，普通的索引赋值会失效，但 at 可以解决。

In [ ]:
import numpy as np

arr = np.arange(1, 6) # [1, 2, 3, 4, 5]

# 1. Reduce (求和)
print("Reduce (Add):", np.add.reduce(arr)) # 15

# 2. Accumulate (阶乘效果)
print("Accumulate (Multiply):", np.multiply.accumulate(arr))
# 输出: [1, 2, 6, 24, 120]

# 3. Outer (两两差值矩阵)
# 计算 arr 中每个数与其他数的差
diff_matrix = np.subtract.outer(arr, arr)
print("\nOuter (Subtract):\n", diff_matrix)

# 4. At (处理索引冲突)
data = np.zeros(5, dtype=int)
indices = [0, 0, 0, 1] # 索引 0 出现了 3 次
# 错误写法：data[indices] += 1
# 这只会让 data[0] 变成 1，因为 NumPy 先读取 data[0] 三次，加 1，然后赋值回去三次
data[indices] += 1
print("普通索引赋值:", data)

# 正确写法：使用 at
data = np.zeros(5, dtype=int)
np.add.at(data, indices, 1) # 在 indices 指定的位置，原地加 1
print("Ufunc.at 赋值:", data) # data[0] 变成了 3

Reduce (Add): 15
Accumulate (Multiply): [  1   2   6  24 120]

Outer (Subtract):
 [[ 0 -1 -2 -3 -4]
 [ 1  0 -1 -2 -3]
 [ 2  1  0 -1 -2]
 [ 3  2  1  0 -1]
 [ 4  3  2  1  0]]
普通索引赋值: [1 1 0 0 0]
Ufunc.at 赋值: [3 1 0 0 0]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt # 如果你想画图的话

# 设定参数
n_walks = 5000  # 模拟 5000 个粒子
n_steps = 1000  # 每个粒子走 1000 步

print(f"开始模拟 {n_walks} 个粒子的 {n_steps} 步随机漫步...")

# 1. 生成步骤 (Steps)
# 使用 rng.integers 生成 0 或 1，然后将 0 映射为 -1
rng = np.random.default_rng(seed=101)
draws = rng.integers(0, 2, size=(n_walks, n_steps))
steps = np.where(draws > 0, 1, -1) # 1 或 -1

# 2. 计算轨迹 (Walks)
# 核心：使用 accumulate (cumsum) 计算每一步后的位置
# axis=1 表示沿着时间轴累积
walks = np.add.accumulate(steps, axis=1)

print(f"轨迹形状: {walks.shape}") # (5000, 1000)

# 3. 统计分析
# 问题 A: 每个粒子离起点的最大距离 (Max absolute distance)
# 先取 abs (Ufunc)，再取 max (reduce)
max_dist = np.abs(walks).max(axis=1)
print(f"平均最大偏离距离: {max_dist.mean():.2f}")

# 问题 B: 哪个粒子最狂野？(走得最远)
wildest_walk_idx = max_dist.argmax()
print(f"最狂野的粒子 ID: {wildest_walk_idx} (最大距离: {max_dist[wildest_walk_idx]})")

# 问题 C: 穿越 30 步大关的最短时间
# 我们要找每个粒子第一次到达 +30 或 -30 的步数
# 这是一个布尔索引 + argmax 的高级用法
hits_30 = (np.abs(walks) >= 30)
# any(axis=1) 检查该行是否有 True
crossing_mask = hits_30.any(axis=1)
print(f"有多少个粒子到达过 30 的距离: {crossing_mask.sum()}")

# 选出那些到达过的粒子，找出第一次到达的时间 (argmax 返回第一个 True 的索引)
crossing_times = hits_30[crossing_mask].argmax(axis=1)
print(f"平均到达 30 距离所需步数: {crossing_times.mean():.1f}")

开始模拟 5000 个粒子的 1000 步随机漫步...
轨迹形状: (5000, 1000)
平均最大偏离距离: 39.10
最狂野的粒子 ID: 1334 (最大距离: 114)
有多少个粒子到达过 30 的距离: 3396
平均到达 30 距离所需步数: 501.6
