<a href="https://colab.research.google.com/github/kuuuun/python_jupyter_notes/blob/main/chapter08_LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# chapter08 线性代数

In [2]:
import numpy as np

矩阵 * 矩阵 就是矩阵乘法  
矩阵 * 向量 就是矩阵的变换  
向量 * 向量 就是向量的点积

In [3]:
# 定义两个矩阵
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("矩阵 A:\n", A)
print("矩阵 B:\n", B)

# 1. 逐元素乘法 (*)
# 对应位置相乘：1*5, 2*6, ...
print("\n逐元素乘法 (A * B):\n", A * B)

# 2. 矩阵乘法 (@)
# 行乘列：1*5+2*7, 1*6+2*8, ...
print("\n矩阵乘法 (A @ B):\n", A @ B)

# 3. 向量的点积
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
# 1*4 + 2*5 + 3*6 = 32
print(f"\n向量内积 (v1 @ v2): {v1 @ v2}")

矩阵 A:
 [[1 2]
 [3 4]]
矩阵 B:
 [[5 6]
 [7 8]]

逐元素乘法 (A * B):
 [[ 5 12]
 [21 32]]

矩阵乘法 (A @ B):
 [[19 22]
 [43 50]]

向量内积 (v1 @ v2): 32


## numpy.linalg 工具箱

|函数|	描述|	数学含义|
|---|---|---|
|np.linalg.inv(A)|	求逆矩阵	|A−1A^{-1} A − 1|
|np.linalg.det(A)|	求行列式	|$|
|np.linalg.norm(A)|	求范数（模长）|	∣A∣|A| ∣ A ∣|
|np.linalg.eig(A)|	特征值分解|	Av=λvAv = \lambda v A v = λ v|
|np.linalg.svd(A)|	奇异值分解|	SVD|
|np.linalg.solve(A, b)|	解方程组|	Ax=bAx = b A x = b|


In [3]:
# 系数矩阵 A
A = np.array([[3, 1],
              [1, 2]])
# 结果向量 b
b = np.array([9, 8])

# 错误做法（不推荐）：显式求逆
# x_bad = np.linalg.inv(A) @ b

# 正确做法：使用 solve
x = np.linalg.solve(A, b)

print(f"解得: x={x[0]:.1f}, y={x[1]:.1f}")

# 验证结果: A @ x 应该等于 b
# 使用 np.allclose 比较浮点数，不要用 ==
is_correct = np.allclose(A @ x, b)
print(f"验证结果是否正确: {is_correct}")

解得: x=2.0, y=3.0
验证结果是否正确: True


In [4]:
# 创建一个对称矩阵（对称矩阵的特征向量总是正交的，性质很好）
M = np.array([[1, 2],
              [2, 1]])

# 计算特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(M)

print("特征值:", eigenvalues)
print("特征向量 (每一列是一个向量):\n", eigenvectors)

# 验证: M @ v = lambda * v
v0 = eigenvectors[:, 0]
lambda0 = eigenvalues[0]

lhs = M @ v0           # 左边: 矩阵 x 向量
rhs = lambda0 * v0     # 右边: 标量 x 向量

print("\n验证特征值性质:", np.allclose(lhs, rhs))

特征值: [ 3. -1.]
特征向量 (每一列是一个向量):
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

验证特征值性质: True


## 高维矩阵乘法

In [3]:
# 模拟 10 个样本，每个样本是一个 2x3 的矩阵
A_batch = np.random.rand(10, 2, 3)

# 模拟 10 个样本，每个样本是一个 3x4 的矩阵
B_batch = np.random.rand(10, 3, 4)

# 我们想对这 10 个样本分别做矩阵乘法
# 结果应该是 (10, 2, 4)
C_batch = A_batch @ B_batch

print(f"A 形状: {A_batch.shape}")
print(f"B 形状: {B_batch.shape}")
print(f"结果形状: {C_batch.shape}")

# 验证第一个样本
# C_batch[0] 应该等于 A_batch[0] @ B_batch[0]
print("验证 Batch 0:", np.allclose(C_batch[0], A_batch[0] @ B_batch[0]))

A 形状: (10, 2, 3)
B 形状: (10, 3, 4)
结果形状: (10, 2, 4)
验证 Batch 0: True


## 矩阵乘法的原则

矩阵乘法是线性代数中非常核心且规则独特的运算。简单来说，它的核心原则可以概括为 **“前行后列要相等，对应相乘再相加”**。

为了让你更清晰地掌握这一原则，我将其拆解为以下几个关键点：

### 1. 前提条件：维度匹配
这是两个矩阵能否相乘的“入场券”。
*   **规则**：第一个矩阵（左矩阵）的**列数**必须等于第二个矩阵（右矩阵）的**行数**。
*   **表示**：若矩阵 $A$ 的维度是 $m \times n$（$m$ 行，$n$ 列），矩阵 $B$ 的维度是 $p \times q$（$p$ 行，$q$ 列），那么只有当 **$n = p$** 时，$A \times B$ 才有定义。

### 2. 结果维度：外侧尺寸
如果两个矩阵满足了相乘条件，结果矩阵的大小由“外侧”的数字决定。
*   **规则**：乘积矩阵 $C = A \times B$ 的行数等于左矩阵 $A$ 的行数，列数等于右矩阵 $B$ 的列。
*   **公式**：$(m \times n) \times (n \times q) = (m \times q)$
*   **记忆法**：中间的维度“抵消”了，剩下外侧的维度构成新矩阵。

### 3. 元素计算：点积法则
这是矩阵乘法最核心的计算步骤。
*   **规则**：结果矩阵 $C$ 中第 $i$ 行第 $j$ 列的元素 $C_{ij}$，等于 **矩阵 $A$ 的第 $i$ 行** 与 **矩阵 $B$ 的第 $j$ 列** 对应元素乘积之和。
*   **公式**：
    $$ C_{ij} = \sum_{k=1}^{n} A_{ik} \times B_{kj} $$
*   **通俗理解**：把 $A$ 的一行“躺平”，去和 $B$ 的一列“竖立”进行配对相乘，最后加起来。

---

### 📊 原则速查表

| 原则类型 | 具体描述 | 示例 |
| :--- | :--- | :--- |
| **可乘性** | 左矩阵的**列** = 右矩阵的**行** | $A_{(2 \times \mathbf{3})} \times B_{(\mathbf{3} \times 4)}$ ✅ (可乘) |
| **结果形状** | 结果的行 = 左矩阵的行结果的列 = 右矩阵的列 | $(2 \times 3) \times (3 \times 4) = (2 \times 4)$ |
| **元素计算** | $C_{ij} =$ 左矩阵第 $i$ 行 $\cdot$ 右矩阵第 $j$ 列 | $C_{11} = A_{11}B_{11} + A_{12}B_{21} + ...$ |

---

### ⚠️ 两个重要的“坑”

1.  **不满足交换律 (AB ≠ BA)**
    矩阵乘法的顺序绝对不能随意调换。
    *   **可能不可乘**：$A \times B$ 可能合法，但 $B \times A$ 可能因为维度不匹配而非法。
    *   **结果不同**：即使两者都合法，计算出的结果通常也是完全不同的。

2.  **满足结合律与分配律**
    *   **结合律**：$(AB)C = A(BC)$
    *   **分配律**：$A(B+C) = AB + AC$

### 🧮 举个简单的例子
假设 $A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ ($2 \times 2$), $B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$ ($2 \times 2$)。
计算 $C_{11}$（第一行第一列）：
*   取 $A$ 的第一行 $[1, 2]$。
*   取 $B$ 的第一列 $\begin{bmatrix} 5 \\ 7 \end{bmatrix}$。
*   计算：$1 \times 5 + 2 \times 7 = 5 + 14 = 19$。

希望这个总结能帮你彻底理解矩阵乘法的原则！
