<a href="https://colab.research.google.com/github/kuuuun/python_jupyter_notes/blob/main/chapter07_%E7%BB%9F%E8%AE%A1%E4%B8%8E%E8%81%9A%E5%90%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# chapter07 统计与聚合

In [3]:
import numpy as np

In [1]:
# 生成一个模拟数据：3个班级，每个班级 4 名学生的考试成绩
rng = np.random.default_rng(42)
scores = rng.integers(60, 100, size=(3, 4))

print("原始成绩单:\n", scores)

# 1. 全局聚合
# 不指定 axis，就把所有数字当成一大袋子数
total_score = np.sum(scores)
avg_score = np.mean(scores)

print(f"\n所有分数的总和: {total_score}")
print(f"全校平均分: {avg_score:.2f}")

原始成绩单:
 [[63 90 86 77]
 [77 94 63 87]
 [68 63 81 99]]

所有分数的总和: 948
全校平均分: 79.00
