<a href="https://colab.research.google.com/github/kuuuun/python_jupyter_notes/blob/main/chapter08_LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# chapter08 线性代数

In [2]:
import numpy as np

矩阵 * 矩阵 就是矩阵乘法  
矩阵 * 向量 就是矩阵的变换  
向量 * 向量 就是向量的点积

In [3]:
# 定义两个矩阵
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("矩阵 A:\n", A)
print("矩阵 B:\n", B)

# 1. 逐元素乘法 (*)
# 对应位置相乘：1*5, 2*6, ...
print("\n逐元素乘法 (A * B):\n", A * B)

# 2. 矩阵乘法 (@)
# 行乘列：1*5+2*7, 1*6+2*8, ...
print("\n矩阵乘法 (A @ B):\n", A @ B)

# 3. 向量的点积
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
# 1*4 + 2*5 + 3*6 = 32
print(f"\n向量内积 (v1 @ v2): {v1 @ v2}")

矩阵 A:
 [[1 2]
 [3 4]]
矩阵 B:
 [[5 6]
 [7 8]]

逐元素乘法 (A * B):
 [[ 5 12]
 [21 32]]

矩阵乘法 (A @ B):
 [[19 22]
 [43 50]]

向量内积 (v1 @ v2): 32
