# transpose

In [10]:
# 2D transpose
import numpy as np
arr = np.arange(6).reshape(2,3)
print(f"origin:\n{arr}")
print(f"transpose:\n{arr.transpose((1,0))}")
print(f"transpose:\n{arr.T}")

origin:
[[0 1 2]
 [3 4 5]]
transpose:
[[0 3]
 [1 4]
 [2 5]]
transpose:
[[0 3]
 [1 4]
 [2 5]]


> axis0=i was 2 blocks, axis1=j was 3blocks, axis2=k was 4blocks

In [13]:
# 3D tanspose
arr = np.arange(24).reshape(2,3,4)
print(f"origin:\n{arr}")
# ignore k, transpose i and j
print(f"transpose:\n{arr.transpose((1,0,2))}")
# shape(2,4,3)
# k轴换为j轴, shape:4->3. 在j轴的三组里，每组挑一个。共8个，再分2大组，每组4个
# shape(3,4,2)
print(f"transpose:\n{arr.transpose((0,2,1))}")
# k轴换为i轴, shape:4->2. 在i轴的两组里，每组挑一个。共12个，在分3大组，每组4个 
print(f"transpose:\n{arr.transpose((1,2,0))}")

origin:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
transpose:
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
transpose:
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]
transpose:
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
