# Index

## python list index

`seq[start:end:step]`

In [2]:
import numpy as np

In [2]:
# 二维（3 x 3）
arr2d = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]
# 第一行和第三行
print(arr2d[0::2])

[[1, 2, 3], [7, 8, 9]]


In [3]:
# 期望：
# 行方向：第一行和第三行，列方向：第一列和第三列
# print(arr2d[0::2,0::2])
# 报错： TypeError: list indices must be integers or slices, not tuple

## numpy basic index

In [4]:
# 一维数组
arr1d = np.array([1, 2, 3, 4, 5])
# 访问第 2 个元素 → 2
print(arr1d[1])

# 二维数组（3 x 3）
arr2d = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])
# 访问第 2 行、第 3 列 → 6
print(arr2d[1][2])

# 三维数组（2 x 3 x 3）
arr3d = np.array(
    [[[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]],

     [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]])
# 访问第 1 层、第 2 行、第 3 列 → 6
print(arr3d[0][1][2])

2
6
6


In [5]:
# 第一层
print(arr3d[0])  # [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# 第一层第二行
print(arr3d[0, 1])  # [4, 5, 6]
# 第一层第二行第三列
print(arr3d[0, 1, 2])  # 6

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
6


### slice

`arr[start:end:step, start:end:step, ...]`

In [3]:
arr2d = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

# 先取所有行，再取第 2 列：
print(arr2d[:, 1]) #  [2, 5, 8]
# 取第 2 行到末尾，再取第 2 列到末尾
print(arr2d[1:, 1:]) # [[5, 6], [8, 9]]
# 先每隔一行取一次，再取所有列
print(arr2d[::2, :]) # [[1, 2, 3], [7, 8, 9]]

[2 5 8]
[[5 6]
 [8 9]]
[[1 2 3]
 [7 8 9]]


>注意，一个数组只能写一个省略号，多个会报错 `IndexError` ：

In [7]:
# arr3d[..., 0,...,]   # IndexError: an index can only have a single ellipsis ('...')

## 掩码

In [5]:
# 一维数组
arr = np.array([10, 20, 30, 40, 50, 60])

# 单条件筛选：选择大于 30 的元素
condition1 = arr > 30
print(condition1)
# [False False False  True  True  True]

result = arr[condition1]  # 等价于 arr[arr > 30]
print( result)
# 输出: [40 50 60]

# 多条件组合：选择 20 ~ 50 之间的元素
condition2 = (arr > 20) & (arr < 50)
result = arr[condition2]
print(result)

[False False False  True  True  True]
[40 50 60]
[30 40]


> 掩码需要提供真假列表

In [14]:
arr = np.arange(12).reshape(3,4)
print(arr)

row_mask = arr>1
result = arr[row_mask]
print(result)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2  3  4  5  6  7  8  9 10 11]
